### General
arrowParens: always
tabWidth: 4
useTabs: false
requirePragma: false
insertPragma:
  false

### PHP
phpVersion: "8.0"
trailingCommaPHP: true
braceStyle: psr-2

### Pattern-specific
overrides:
  - files: "src/**/*.php"
    options:
      singleQuote: true
      printWidth: 120
  - files: "src/**/*.blade.php"
    options:
      parser: "blade"
      printWidth: 120
